repos:
  # Python hooks
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  # C++ hooks
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
      - id: clang-format
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
    - id: cmake-format
  # general hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: pretty-format-json
        args: [--autofix]
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
